language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t sunnymishra/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true sunnymishra/docker-react npm run test